# Generated by Django 3.1.3 on 2020-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201113_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='total_amount',
            field=models.FloatField(default=13.0),
            preserve_default=False,
        ),
    ]
