# Generated by Django 2.0.13 on 2020-11-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('primary_category', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_text', models.CharField(max_length=300)),
                ('product_detail', models.TextField()),
                ('main_image', models.ImageField(upload_to='imag')),
                ('sub_image_1', models.ImageField(blank=True, null=True, upload_to='imag')),
                ('sub_image_2', models.ImageField(blank=True, null=True, upload_to='imag')),
                ('sub_image_3', models.ImageField(blank=True, null=True, upload_to='imag')),
                ('price', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Offer')),
            ],
        ),
    ]
