# Generated by Django 2.0.13 on 2020-11-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201107_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
