# Generated by Django 2.0.13 on 2020-11-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201107_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='ongoing',
        ),
    ]
